/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.90
 * Generated at: 2024-06-27 21:03:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,user-scalable=yes,\r\n");
      out.write(" maximum-scale=1.0,minimum-scale=1.0\">\r\n");
      out.write(" <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write(" <link rel=stylesheet type=text/css href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css\">\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"home.css\">\r\n");
      out.write(" <link rel=\"stylesheet\"  href=\"css/bootstrap.css\">\r\n");
      out.write(" <script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js\" integrity=\"sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js\" integrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<title>EasyBus</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("  \r\n");
      out.write("  <a href=\"\" class=\"navbar-brand\"><img src=\"IMAGES/logo-modified.png\"  class=\"img-fluid mr-2 custom-logo\">EasyBus</a>\r\n");
      out.write(" \r\n");
      out.write("  <div class=\"collapse navbar-collapse justify-content-center\">\r\n");
      out.write("  <ul class=\"navbar-nav\">\r\n");
      out.write("  \r\n");
      out.write("      <li class=\"nav-item active\"><a href=\"home.jsp\" class=\"nav-link\">Home</a> </li>\r\n");
      out.write("      <li class=\"nav-item\"><a href=\"MyRes.jsp\" class=\"nav-link\">MyReservation</a> </li>\r\n");
      out.write("      <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">Contact</a> </li>\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"\" id=\"navbarDropdownMenuLink\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("      Account\r\n");
      out.write("      </a>\r\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("      \r\n");
      out.write("          <a class=\"dropdown-item\" href=\"insertUser.jsp\">SignUp</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"userlogin.jsp\">Login</a>\r\n");
      out.write("         \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("  \r\n");
      out.write("  </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("      <form class=\"form-inline my-2 my-lg-0\" justify-content-end>\r\n");
      out.write("      <input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("      <button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">Search</button>\r\n");
      out.write("      </form>\r\n");
      out.write("  \r\n");
      out.write("  </nav>\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("  <div class=\"carousel\">\r\n");
      out.write("  \r\n");
      out.write("  <div id=\"carouselExampleCaptions\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("    <ol class=\"carousel-indicators\">\r\n");
      out.write("      <li data-target=\"#carouselExampleCaptions\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("      <li data-target=\"#carouselExampleCaptions\" data-slide-to=\"1\"></li>\r\n");
      out.write("      <li data-target=\"#carouselExampleCaptions\" data-slide-to=\"2\"></li>\r\n");
      out.write("    </ol>\r\n");
      out.write("    <div class=\"carousel-inner\">\r\n");
      out.write("      <div class=\"carousel-item active\">\r\n");
      out.write("        <img src=\"IMAGES/bus8.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("        <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("          <h5 class=\" font-weight-bold\">Travel with Confidence</h5>\r\n");
      out.write("          <p class=\" font-weight-bold\">Travel with confidence knowing that our bus services are safe and reliable. We're committed to providing you with a comfortable journey</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>  \r\n");
      out.write("      <div class=\"carousel-item\">\r\n");
      out.write("        <img src=\"IMAGES/bus10.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("        <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("          <h5 class=\" font-weight-bold\">Quick and Easy Booking</h5>\r\n");
      out.write("          <p class=\" font-weight-bold\">Experience the simplicity of online bus ticket reservation. With EasyBus, booking your bus tickets has never been this straightforward. Say goodbye to long queues and hello to convenience</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"carousel-item \">\r\n");
      out.write("        <img src=\"IMAGES/67.png\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("        <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("          <h5 class=\"font-weight-bold text-primary\">24/7 Customer Support</h5>\r\n");
      out.write("          <p class=\" font-weight-bold text-primary\">Questions? Concerns? We're here for you 24/7. Our dedicated customer support team is ready to assist you at any time, ensuring you have a smooth and hassle-free journey.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>  \r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("    <a class=\"carousel-control-prev\" href=\"#carouselExampleCaptions\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("      <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("      <span class=\"sr-only\">Previous</span>\r\n");
      out.write("    </a>\r\n");
      out.write("    <a class=\"carousel-control-next\" href=\"#carouselExampleCaptions\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("      <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("      <span class=\"sr-only\">Next</span>\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("   \r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("   <div class=\"center-form\">\r\n");
      out.write("  \r\n");
      out.write("   <div class=\"card card-sm \">\r\n");
      out.write("   <div class=\"card-body\">\r\n");
      out.write("    <form action=\"view\" method=\"post\" class=\"form-inline\">\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("       <div class=\"form-group row\">\r\n");
      out.write("         <label for=\"departureLocation\" class=\"col-sm-2 col-form-label\" ><h5 class=\" font-weight-bold text-dark\">From</h5></label>\r\n");
      out.write("         <div class=\"col-sm-2\">\r\n");
      out.write("            <select class=\"form-select form-select-sm\" name=\"departureLocation\" required>\r\n");
      out.write("            <option ></option>\r\n");
      out.write("            <option value=\"Panadura\">Panadura</option>\r\n");
      out.write("            <option value=\"Kottawa\">Kottawa</option>\r\n");
      out.write("            <option value=\"Galle\">Galle</option>\r\n");
      out.write("            <option value=\"Maharagama\">Maharagama</option>\r\n");
      out.write("          \r\n");
      out.write("            </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("       <div class=\"form-group row\">\r\n");
      out.write("         <label for=\"arrivalLocation\" class=\"col-sm-2 col-form-label\"><h5 class=\" font-weight-bold text-dark\">To</h5></label>\r\n");
      out.write("         <div class=\"col-sm-2\">\r\n");
      out.write("            <select class=\"form-select form-select-sm\" name=\"arrivalLocation\" required>\r\n");
      out.write("            <option ></option>\r\n");
      out.write("            <option value=\"Dehiwala\">Dehiwala</option>\r\n");
      out.write("            <option value=\"Pannipitiya\">Pannipitiya</option>\r\n");
      out.write("            <option value=\"Colombo\">Colombo</option>\r\n");
      out.write("            <option value=\"Nugegoda\">Nugegoda</option>\r\n");
      out.write("         \r\n");
      out.write("            </select>\r\n");
      out.write("            </div>\r\n");
      out.write("               </div>\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("       <div class=\"form-group row\">\r\n");
      out.write("         <label for=\"departureDate\" class=\"col-sm-3 col-form-label\"><h5 class=\" font-weight-bold text-dark\">Date</h5></label>\r\n");
      out.write("         <div class=\"col-sm-3\">\r\n");
      out.write("             <select class=\"form-select form-select-sm\" name=\"departureDate\" required>\r\n");
      out.write("             <option ></option>\r\n");
      out.write("             <option value=\"2022-10-01\">2022-10-01</option>\r\n");
      out.write("             <option value=\"2022-10-02\">2022-10-02</option>\r\n");
      out.write("             <option value=\"2022-10-03\">2022-10-03</option>\r\n");
      out.write("             <option value=\"2022-10-04\">2022-10-04</option>\r\n");
      out.write("           \r\n");
      out.write("             </select>\r\n");
      out.write("             </div>\r\n");
      out.write("             </div>\r\n");
      out.write("         \r\n");
      out.write("          \r\n");
      out.write("             <div class=\"form-group row\">\r\n");
      out.write("             <div class=\"col-sm-12\">\r\n");
      out.write("         <input class=\"btn btn-dark btn-block font-weight-bold fs-5\" type=\"submit\" name=\"view\" value=\"view\">\r\n");
      out.write("         </div>\r\n");
      out.write("           </div>\r\n");
      out.write("      \r\n");
      out.write("       </form>\r\n");
      out.write("       \r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("<div class=\"heading mt-0\">\r\n");
      out.write("  <h1>About Us</h1>\r\n");
      out.write("  <p>EasyBus streamline the entire booking process, reduce the risk of overbooking, and enhance operational efficiency for bus companies, while providing passengers with the flexibility to plan their trips with ease</p>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write(" \r\n");
      out.write(" <section class=\"about\">\r\n");
      out.write("        <div class=\"about-image\">\r\n");
      out.write("           <img src=\"IMAGES/about.jpg\">\r\n");
      out.write("           </div>\r\n");
      out.write("        <div class=\"about-content\">\r\n");
      out.write("        <input id=\"ch\" type=\"checkbox\" checked>\r\n");
      out.write("           <h2>Discover EasyBus: Your Convenient Gateway to Hassle-Free Bus Ticket Reservations </h2>\r\n");
      out.write("           <p>At EasyBus, we're dedicated to providing you with a seamless and reliable bus ticket booking experience. Our mission is to make your journey as comfortable and stress-free as possible. With a commitment to safety and efficiency, we offer a wide range of destinations and routes to suit your travel needs.\r\n");
      out.write("              We understand that convenience is key, and that's why we've made online booking a breeze. Say goodbye to long queues and hello to quick and easy reservations. Our user-friendly platform allows you to select your departure and arrival locations, choose your travel date, and secure your seat in just a few clicks.\r\n");
      out.write("              Safety is our top priority. We ensure that our bus services are well-maintained, and our drivers are experienced and professional. You can travel with confidence, knowing that your well-being is our concern.......\r\n");
      out.write("              </p>\r\n");
      out.write("              <div class=\"content\">\r\n");
      out.write("           <p> If you ever have questions or concerns, our dedicated customer support team is here for you 24/7. We believe in providing assistance at any time to ensure that your journey is smooth and hassle-free. Your satisfaction is our success.\r\n");
      out.write("              Easy Bus is not just a bus ticket reservation system; it's your travel companion. We're passionate about promoting sustainable and environmentally friendly travel. As we expand our services, we're committed to minimizing our impact on the environment and contributing to a greener, healthier future.\r\n");
      out.write("              Thank you for choosing Easy Bus as your travel partner. We look forward to serving you and making your journey a memorable one. </p>\r\n");
      out.write("           <label for=\"ch\" class=\"read-more\">Show less</label>\r\n");
      out.write("              </div>\r\n");
      out.write("          \r\n");
      out.write("           <label for=\"ch\" class=\"read-more\">Read More</label>\r\n");
      out.write("          \r\n");
      out.write("               \r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("     </section>\r\n");
      out.write(" <hr>   \r\n");
      out.write("     <div class=\"section\">\r\n");
      out.write("        <div class=\"title\">\r\n");
      out.write("            <h1>Why EasyBus: Your Ultimate Travel Companion</h1>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class=\"services\">\r\n");
      out.write("      \r\n");
      out.write("          <div class=\"cas\">\r\n");
      out.write("          \r\n");
      out.write("             <div class=\"icon\">\r\n");
      out.write("               <i class=\"fa fa-ticket\" style=\"font-size: 35px;\"></i>\r\n");
      out.write("             </div>\r\n");
      out.write("            \r\n");
      out.write("              <h2>BookEasy</h2>\r\n");
      out.write("             \r\n");
      out.write("              <p>With just a few clicks, you can secure your tickets, streamlining your journey for ultimate convenience. We believe in hassle-free travel, making your trip memorable.</p>\r\n");
      out.write("           \r\n");
      out.write("             \r\n");
      out.write("             \r\n");
      out.write("              </div>  \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("        \r\n");
      out.write("          <div class=\"cas\">\r\n");
      out.write("             <div class=\"icon\">\r\n");
      out.write("               <i class=\"fa fa-shield\" style=\"font-size: 35px;\"></i>\r\n");
      out.write("             </div>\r\n");
      out.write("              <h2>SafeRide</h2>\r\n");
      out.write("              <p> SafeRide ensures your peace of mind. Prioritizing safety, our well-maintained buses and experienced drivers guarantee your well-being and a secure journey.</p>\r\n");
      out.write("              \r\n");
      out.write("          </div>\r\n");
      out.write("         \r\n");
      out.write("          \r\n");
      out.write("        \r\n");
      out.write("          <div class=\"cas\">\r\n");
      out.write("             <div class=\"icon\">\r\n");
      out.write("               <i class=\"fa fa-map\" style=\"font-size: 35px;\"></i>\r\n");
      out.write("             </div>\r\n");
      out.write("              <h2>GoWide</h2>\r\n");
      out.write("              <p>GoWide offers diverse routes. Whether you commute or explore leisurely, Easy Bus has you covered. Countless options make your journey choices abundant and exciting.</p>\r\n");
      out.write("             \r\n");
      out.write("          </div>\r\n");
      out.write("   \r\n");
      out.write("      \r\n");
      out.write("       </div>\r\n");
      out.write("     \r\n");
      out.write("     </div>\r\n");
      out.write("     <hr>\r\n");
      out.write("     <div class=\"client-wrap\">\r\n");
      out.write("        <h1>Our Partners</h1>\r\n");
      out.write("        <hr/>\r\n");
      out.write("        <div class=\"client-in\">\r\n");
      out.write("         <ul> \r\n");
      out.write("            <li>\r\n");
      out.write("            <img src=\"IMAGES/12.png\"  alt=\"\" />\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("            <img src=\"IMAGES/13.png\"  alt=\"\" />\r\n");
      out.write("            </li>\r\n");
      out.write("             <li>\r\n");
      out.write("            <img src=\"IMAGES/17.png\"  alt=\"\" />\r\n");
      out.write("            </li>\r\n");
      out.write("             <li>\r\n");
      out.write("            <img src=\"IMAGES/15.png\"  alt=\"\" />\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("            <img src=\"IMAGES/14.png\"  alt=\"\" />\r\n");
      out.write("            </li>\r\n");
      out.write("             \r\n");
      out.write("         </ul>\r\n");
      out.write("       </div> \r\n");
      out.write("     </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     <br>\r\n");
      out.write("     <br>\r\n");
      out.write("     <footer style=\"background-color: #000;\">\r\n");
      out.write("     <div class=\"footerContainer\">\r\n");
      out.write("       <div class=\"socialIcons\">\r\n");
      out.write("         <a href=\"#\"><i class=\"fa-brands fa-facebook\"></i></a>\r\n");
      out.write("         <a href=\"#\"><i class=\"fa-brands  fa-twitter\"></i></a>\r\n");
      out.write("         <a href=\"#\"><i class=\"fa-brands  fa-instagram\"></i></a>\r\n");
      out.write("        <a href=\"#\"><i class=\"fa-brands  fa-youtube\"></i></a>\r\n");
      out.write("        <a href=\"#\"><i class=\"fa-brands  fa-google-plus\"></i></a>\r\n");
      out.write("        <a href=\"#\"><i class=\"fab fa-cc-visa\"></i></a>\r\n");
      out.write("        <a href=\"#\"><i class=\"fab fa-cc-mastercard\"></i></a>\r\n");
      out.write("        <a href=\"#\"><i class=\"fab fa-cc-paypal\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("     <div class=\"footerNav\">\r\n");
      out.write("       <ul>\r\n");
      out.write("         <li><a href=\"FAQ.jsp\" >FAQ</a></li>\r\n");
      out.write("          <li><a href=\"T&C.jsp\" >T & C</a></li>\r\n");
      out.write("       \r\n");
      out.write("      \r\n");
      out.write("       </ul>\r\n");
      out.write("    \r\n");
      out.write("     </div>\r\n");
      out.write("       \r\n");
      out.write("       <div class=\"footerBottom\" style=\"text-align:center; ;\">\r\n");
      out.write("          <p>Copyright &copy;2023;Designed by <span class=\"designer\">KUMARAGE D.C.K.</span></p>\r\n");
      out.write("       \r\n");
      out.write("       </div>\r\n");
      out.write("     \r\n");
      out.write("     </div>\r\n");
      out.write("      </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
