/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.90
 * Generated at: 2024-06-27 21:03:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MyRes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Check My Reservation</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css1/ReservationCheck.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css1/footer.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css1/nav.css\">\r\n");
      out.write("<link rel=stylesheet type=text/css href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("  \r\n");
      out.write("  <a href=\"\" class=\"navbar-brand\"><img src=\"mg/logo-modified.png\"  class=\"img-fluid mr-2 custom-logo\">EasyBus</a>\r\n");
      out.write(" \r\n");
      out.write("  <div class=\"collapse navbar-collapse justify-content-center\">\r\n");
      out.write("  <ul class=\"navbar-nav\">\r\n");
      out.write("  \r\n");
      out.write("      <li class=\"nav-item \"><a href=\"home.jsp\" class=\"nav-link\">Home</a> </li>\r\n");
      out.write("      <li class=\"nav-item active\"><a href=\"MyRes.jsp\" class=\"nav-link\">MyReservation</a> </li>\r\n");
      out.write("      <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">Contact</a> </li>\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a class=\"nav-link dropdown-toggle\" href=\"\" id=\"navbarDropdownMenuLink\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("      Account\r\n");
      out.write("      </a>\r\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("      \r\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">SignUp</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Login</a>\r\n");
      out.write("         \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("  \r\n");
      out.write("  </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("      <form class=\"form-inline my-2 my-lg-0\" justify-content-end>\r\n");
      out.write("      <input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("      <button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">Search</button>\r\n");
      out.write("      </form>\r\n");
      out.write("  \r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("   <section class=\"Form my-4 mx-5\">\r\n");
      out.write("     <div class=\"container\">\r\n");
      out.write("        <div class=\"row no-gutters\">\r\n");
      out.write("             <div class=\"col-lg-5\">\r\n");
      out.write("                <img alt=\"\"  class=\"img-fluid\" src=\"mg/resCheck.jpg\">\r\n");
      out.write("             </div>\r\n");
      out.write("             <div class=\"col-lg-7 px-5 pt-5\">\r\n");
      out.write("               <h3>Check your reservation details</h3>\r\n");
      out.write("                <form action=\"nice\" method=\"post\">\r\n");
      out.write("                    <div class=\"form-row\">\r\n");
      out.write("                        <div class=\"col-lg-7\">\r\n");
      out.write("                            Reference Id<br>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control my-3 p-4\" name=\"ref_id\" placeholder=\"Enter your Reference Id\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                     <div class=\"form-row\">\r\n");
      out.write("                        <div class=\"col-lg-7\">\r\n");
      out.write("                            UserName<br>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control  my-3 p-4\" name=\"uname\" placeholder=\"Enter user name\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-row\">\r\n");
      out.write("                        <div class=\"col-lg-7\">             \r\n");
      out.write("                            <input type=\"submit\" class=\"btn1 mt-3 mb-5\" name=\"submit\" value=\"Find Reservation Details\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("             </div>\r\n");
      out.write("        </div>\r\n");
      out.write("   \r\n");
      out.write("     </div>\r\n");
      out.write("   </section>\r\n");
      out.write("\r\n");
      out.write(" <footer style=\"background-color: #000;\">\r\n");
      out.write("     <div class=\"footerContainer\">\r\n");
      out.write("       <div class=\"socialIcons\">\r\n");
      out.write("         <a href=\"#\"><i class=\"fa-brands fa-facebook\"></i></a>\r\n");
      out.write("         <a href=\"#\"><i class=\"fa-brands  fa-twitter\"></i></a>\r\n");
      out.write("         <a href=\"#\"><i class=\"fa-brands  fa-instagram\"></i></a>\r\n");
      out.write("        <a href=\"#\"><i class=\"fa-brands  fa-youtube\"></i></a>\r\n");
      out.write("        <a href=\"#\"><i class=\"fa-brands  fa-google-plus\"></i></a>\r\n");
      out.write("        <a href=\"#\"><i class=\"fab fa-cc-visa\"></i></a>\r\n");
      out.write("        <a href=\"#\"><i class=\"fab fa-cc-mastercard\"></i></a>\r\n");
      out.write("        <a href=\"#\"><i class=\"fab fa-cc-paypal\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("     <div class=\"footerNav\">\r\n");
      out.write("       <ul>\r\n");
      out.write("         <li><a href=\"FAQ.jsp\" >FAQ</a></li>\r\n");
      out.write("          <li><a href=\"T&C.jsp\" >T & C</a></li>\r\n");
      out.write("       \r\n");
      out.write("      \r\n");
      out.write("       </ul>\r\n");
      out.write("    \r\n");
      out.write("     </div>\r\n");
      out.write("       \r\n");
      out.write("       <div class=\"footerBottom\" style=\"text-align: center;\">\r\n");
      out.write("          <p>Copyright &copy;2023;Designed by <span class=\"designer\">KUMARAGE D.C.K.</span></p>\r\n");
      out.write("       \r\n");
      out.write("       </div>\r\n");
      out.write("     \r\n");
      out.write("     </div>\r\n");
      out.write("      </footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
